### ISSUE TITLE
[🚀FEATURE] New Intermediate project suggestion

### ISSUE THREAD

**Issue by Swarno-Coder** [Swarno-Coder/ShortProjectsUsingJava#3]
Currently, this repo contains some basic Java projects.
I'm looking for a contributor who can contribute to some of the intermediate to advanced-level (Single file) projects using Java.

**Comment by adityaaa009** [comment]
Hello Swano-Coder, I would like to contribute to this.  Can you please assign this to me? Thanks

**Comment by adityaaa009** [comment]
> Currently, this repo contains some basic Java projects. I'm looking for a contributor who can contribute to some of the intermediate to advanced-level (Single file) projects using Java.
Hello Swarno-Coder, I would like to contribute to this. Can you please assign this to me? Thanks

**Comment by Swarno-Coder** [comment]
@adityaaa009 Thanks for your interest.
If you work on any feature or want to add a new feature please create an ISSUE before working.

**Comment by adityaaa009** [comment]
Really sorry, I wasn't aware of it since it was my first Open Source
contribution. I'll keep that in mind.

**Comment by Swarno-Coder** [comment]
@Karanjamwal21 Create an ISSUE if you work on any updation of this feature or want something new to add as project.
