### ISSUE TITLE
[🔗ISSUE] TemperatureConverter.java Incomplete

### ISSUE THREAD

**Issue by Swarno-Coder** [Swarno-Coder/ShortProjectsUsingJava#4]
[TemperatureConverter.java](https://github.com/Swarno-Coder/ShortProjectsUsingJava/blob/master/src/TemperatureConverter.java) is empty.
- Fix this file if you can.
- Add GUI based Temperature converter if you can
- Must use single file for this work done

**Comment by Karanjamwal21** [comment]
I want to update this.
